sudo: required

services:
  - docker

before_install:
  - make

script:
  - make run
  - make test

after_success:
  - make push_quay
  - make push_hub

notifications:
  email: false

env:
  matrix:
    - tag=base
    - tag=app
    - tag=mariadb
    - tag=php-base
    - tag=php-fpm
    - tag=httpd
    - tag=drush
  global:
    - DOCKER_IMAGES="base app mariadb php-base php-fpm httpd drush"
    - DOCKER_REGISTRY=quay.io
    - DOCKER_REPO_USERNAME=labiomed
    - DOCKER_REPO_SLUG=centos7-systemd-amp
