sudo: required

services:
  - docker

before_install:
  - make

script:
  - make run
  - make test

after_success:
  - make push

notifications:
  email: false

env:
  global:
    - DOCKER_REGISTRY=quay.io
    - DOCKER_REPO_USERNAME=labiomed
    - DOCKER_REPO_SLUG=centos7-systemd-amp
