sudo: required

services:
  - docker

before_install:
  - make

script:
  - make run
  - make test

after_success:
  - make push

notifications:
  email: false

env:
  matrix:
  - LOWERCASE_REPO_SLUG=labiomed/centos7-systemd-amp
  global:
  - secure: mvTy1NO0us/u6uTZdauqcBHhxulgS1F5p1w7Yp5Tk1+bt+q/Hwn10oqyZJ9z8BmnX9JapBAPdhsf+fv8pNeyizCDD88WBTuYmnntfrkugZ/1BcUdEdvVJRvMEXQbeR0xs0Y1G6h98ZAXu3/G1wzOlQSTDRijQ3eFMqxmP5s8i/Smo0mOq98Wb/Sz8Ye9fs65WTIafy6qoqbDf1K+1Y63a2Netiu5ZVxVmyVVn7k15yYnHKbmscb7STn5PkPNzYcyHZSaMeas3H54TsbJ4nRAAW8FzfpSV8OKKjwJEQrGUDrV1SLKcMXqfGI/lF8rymhm4BjPj6ZcSTrDPKSRCXSMCZUoGRlYSl2KqoldOpV3f43Kvz9+VqLFQQ8/U6aTwm6oTplCCsyCuPWYfLsFsGChKVfiDo6XFKa80+B51nO+G/zvNfORek1oWqqZisvQOhK5JCeb0/qlVy6+OsNnkUWlSIlnGjDFsJjh2rERRbZUzppULfsc0OfZiWQrZ8lvOF6kah8P4JM+7osCJ/rWKEIcBbZmHFR4WEWe51T3m8jXikQHs8KnZfC52kDpM8VzwB4w8fDGhQDwQbINoj7rhe4nTsr+vMhdPuhH39RxwpO6PVQOFDUv356iT22XO5fYFVNRdxWpobbvqGReEf1pHA2PKRRID/rV/4SQxI/lkzjTExE=
  - secure: nmKIYw0rDBknA9x0rGdzdF7MxyCJ/88Pf3Sjc/RYrkTpS3PSIwXbt0ZwO65BDfXXpspw2t9O1DqghuQkprfsbXMiQY+fTd2vfdFBh1jTTxnklw30qBd6hfMZBpB7p2XKrwRbdWOvlRMNYMMwp6c2LYdJZE0BPWmwYvcVYZ97UXDEOKe+J9tOs8YLGAvV7pOPrhiqo5DJAWuwX7imbOrOEXc1o/klnDahfqS0IHRp1uePdNJ1oGutgcWODBOMirCThsFaWeEV/KehNCugt8vkK1PODVMKUBxemNBJg2NrspUA0oJb/WZ8nDigja0oqEvwikxEEck6pKJpOrPbPoXmpSQ7Dhf88yq7+htY6a609EEERLfjekvI30WiSEiiUI96OJDkBnK3lC2X0amqU+EsU+NxrNk+sGbxRPQCW+LEs3Ly5a8R89JPxki5be5keeXp/4Vi9bL2YMYZxWL8Pu045ay/DI5XE/mJTH4uTcQ8dO10+DbcYdjGnbCZBYebA9zfPrFDoHmkrupq56A4juRADu6hEpQs3zNVhXHhkBjg/ADkH7/nCgE0ia5yQABaB4tl89msO60PlwyTG1s8tO4Iw72+dA+leblFKubNECgLE+4gJURh96ohD7WkUYaIwKszz1reLYzXITBHR9vv9aQndZD58Zf7+Gshfpcs/gt/T34=
  - secure: W5R7ei/R+DagAD9qHhqVQX2mtOTfzrcGMuZrIMtH6NtKrRchFgDDZhWVtLwtF6hvdkdCVJhzTvn2tZ6F8AS+zFrtwEQ9LN7zHoJkAJfPbIBbwAh+IK3DGGYcE3nycbA6P57ybRTgB1u9UAPXJzAp9qLrRXMtizfARZ+jAjAjPrQ7gL3vVeypPmKCnKkdGBrYz3rZ2yfXoL1lSffj0g0y9yCu8vkmQU2UAK+KS8wfUWUt6ZWnIGO3Fe1wm+/XkZgr1clkXkQ/7P8/NpzKCLP1+9M1q++meuWlDpCbESW9iJ838Y4dN/yKNniaBGhRohlXq3aiIpYEGASI25M3xdMX62GJS9MfdnRwm7jll2T/HfQ5+Hc1RhT3ocNt7Hv3eCcobQOQ2WquNkcUbOocXLk8UORXCczd66ybFoS2BX3ZlNg9BjUSpCZ7S6Mgrv9JZxq4oNrVt/G/oSZ3cBDUNu+YzekYaYL7vT1hdWb087KCehZTaK9BU1jcQ17GObjXz7e5TOxLj/gqpOFXmyx+l0Pp+6kjB5IkeO1PynsW14VDe8i4oQwc1gquvs9aWJV0JR+aI4S/mbf6caZX7McybgSj0gs6KGYWo8YoxQTNxyWDRu/bMZjLXIHsmTPqjPy0dcx5kRZAUxHxJ5xeegaWcZ7Js9iE2ZHYTBjypNB46pZEh/w=
