sudo: required

services:
  - docker

before_install:
  - make

install:
  - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

script:
  - make version
  - make test

after_success:
  - push

notifications:
  email: false

env:
  - LOWERCASE_REPO_SLUG=labiomed/centos7-systemd-amp