sudo: required

services:
  - docker

before_install:
  - docker build -t ${DOCKER_REGISTRY}/${DOCKER_REPO_USERNAME}/${DOCKER_REPO_SLUG}:${tag} ${tag}; \

script:
  - docker run -d -v /sys/fs/cgroup:/sys/fs/cgroup:ro ${DOCKER_REGISTRY}/${DOCKER_REPO_USERNAME}/${DOCKER_REPO_SLUG}:${tag} /usr/lib/systemd/systemd

after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then
      docker login -e="${QUAY_EMAIL}" -u="${QUAY_USER}" -p="${QUAY_PASS}" quay.io;
      docker push ${DOCKER_REGISTRY}/${DOCKER_REPO_USERNAME}/${DOCKER_REPO_SLUG}:${tag};
    fi
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then
      docker login -e="${DOCKER_HUB_EMAIL}" -u="${DOCKER_HUB_USER}" -p="${DOCKER_HUB_PASS}";
      docker tag ${DOCKER_REGISTRY}/${DOCKER_REPO_USERNAME}/${DOCKER_REPO_SLUG}:${tag} ${DOCKER_REPO_USERNAME}/${DOCKER_REPO_SLUG}:${tag};
      docker push ${DOCKER_REPO_USERNAME}/${DOCKER_REPO_SLUG}:${tag};
    fi

notifications:
  email: false

env:
  matrix:
    - tag=base
    - tag=app
    - tag=mariadb
    - tag=php-base
    - tag=php-fpm
    - tag=httpd
    - tag=drush
  global:
    - DOCKER_IMAGES="base app mariadb php-base php-fpm httpd drush"
    - DOCKER_REGISTRY=quay.io
    - DOCKER_REPO_USERNAME=labiomed
    - DOCKER_REPO_SLUG=centos7-systemd-amp
