sudo: required

services:
  - docker

before_install:
  - make

script:
  - make run
  - make test

after_success:
  - make push

notifications:
  email: false

env:
  matrix:
  - LOWERCASE_REPO_SLUG=labiomed/centos7-systemd-amp
