sudo: required

services:
  - docker

before_install:
  - make

install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - make version
  - make test

after_success:
  - push

notifications:
  email: false

env:
  - LOWERCASE_REPO_SLUG=labiomed/centos7-systemd-amp
