#!/bin/bash

cd /etc/profile.d/
rm -rf "./environment.env"

while IFS='' read -r line || [[ -n "$line" ]]; do
  echo $(echo "${line}" | sed 's/^export //' | sed 's/\\/\\\\/g') >> "./environment.env";
done < "./environment.sh"
