#!/bin/bash

cd /etc/profile.d/
rm "./environment.env"

while IFS='' read -r line || [[ -n "$line" ]]; do
  echo $(echo "${line}" | sed 's/^export //') >> "./environment.env";
done < "./environment.sh"
